#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       you can use the bash exit status of this script:
#
#           exit /bin/sh -c '. ./gradlew; mydist/bin/myapp'
#
#       POSIX shells will print the exit status of the last command, which is
#       what you want when wrapping the gradlew in a larger script.
#
#   (2) The continued execution of gradlew with the same command will then be
#       faster when more shell start up scripts are cached between calls.
#
##############################################################################

set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd )

APP_HOME="${SCRIPT_DIR:-.}"

exec "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
